version: '3.9'

x-livy-common: &livy-common
  user: root
  build:
    context: .
    dockerfile: livy_dockerfile
  volumes:
    - ./../../spark/jobs:/opt/livy/jobs
    - ./../../spark/configs:/opt/livy/configs
    - ./../../spark/dependencies:/opt/livy/dependencies
    - ./../../spark/tests:/opt/livy/tests
    - ./../../spark/packages.zip:/opt/livy/packages.zip
    - ./containers-data/livy/logs:/opt/livy/logs
    - ./containers-data/livy/work:/opt/livy/work
  env_file:
    - ./.env
    - ./../../spark/.env
  environment:
    &livy-common-env
    LIVY_SERVER_PORT: 8998
    LIVY_SPARK_MASTER: spark://spark-master:7077
    LIVY_SPARK_DEPLOY_MODE: cluster
    LIVY_SERVER_HOST: 0.0.0.0
    SPARK_HOME: /opt/spark
    SPARK_CONF_DIR: /opt/spark/conf
    HADOOP_CONF_DIR: /etc/hadoop/conf
    LIVY_FILE_LOCAL_DIR_WHITELIST: /opt/livy/jobs,/opt/livy/dependencies
    LIVY_SPARK_JARS: /opt/spark/jars/*
    LIVY_SERVER_LOGFILE: /opt/livy/logs/livy-server.out
  platform: linux/amd64
  networks:
    - ${GLOBAL_NETWORK:-services}

services:
  livy-server:
    <<: *livy-common
    container_name: livy-server
    command: |
      bash -c "
        echo 'Starting Livy Server...' &&
        /opt/livy/bin/livy-server start &&
        sleep 10 &&
        echo 'Checking Livy logs...' &&
        tail -f /opt/livy/logs/livy-*.out
      "
    ports:
      - "${LIVY_SERVER_HOST_PORT}:${LIVY_SERVER_HOST_INTERNAL_PORT}"
    depends_on:
      spark-master:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8998/sessions"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 60s
    restart: unless-stopped