version: '3.9'

x-common:
  &common
  env_file:
    - ./.env
  platform: linux/amd64

services:
  postgres_db:
    <<: *common
    image: postgres:${POSTGRES_VERSION:-latest}
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - '${POSTGRES_DB_HOST_PORT}:${POSTGRES_DB_INTERNAL_PORT}'
    volumes:
      - ./containers-data/postgresdb/data/storage:/var/lib/postgresql/data/:z
      - ./scripts/postgresql/airflow_db-init.sh:/docker-entrypoint-initdb.d/airflow_db-init.sh
    networks:
      - ${GLOBAL_NETWORK:-services}